apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: {{ .Values.cassandra.replicas }}
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: "{{ .Values.cassandra.image }}"
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "{{ .Values.cassandra.clusterName }}"
        - name: CASSANDRA_SEEDS
          value: cassandra-0.cassandra.default.svc.cluster.local
        ports:
        - containerPort: 9042
        volumeMounts:
        - name: cassandra-config
          mountPath: /etc/cassandra-config
          readOnly: true
        - name: cassandra-data
          mountPath: /var/lib/cassandra
        resources:
          limits:
            memory: "{{ .Values.cassandra.memoryLimit }}"
            cpu: "{{ .Values.cassandra.cpuLimit }}"
        livenessProbe:          # Check if Cassandra is responsive by executing CQL query
          exec:
            command:
            - cqlsh
            - -e
            - "DESCRIBE KEYSPACES;"
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:           # Check if Cassandra is ready to serve traffic
          exec:
            command:
            - cqlsh
            - -e
            - "SELECT * FROM system_schema.keyspaces;"
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: cassandra-config
        configMap:
          name: cassandra-config
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "{{ .Values.cassandra.storageCapacity }}"