apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: {{ .Values.cassandra.replicas }}
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: {{ .Values.cassandra.image }}
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "{{ .Values.cassandra.clusterName }}"
        ports:
        - containerPort: 9042
        volumeMounts:
          - name:  cassandra-data
            mountPath: /var/lib/cassandra
        resources:
          limits:
            memory: "{{ .Values.cassandra.memoryLimit }}"
            cpu: "{{ .Values.cassandra.cpuLimit }}"
        livenessProbe:
          httpGet:
            path: /health
            port: 9042
        readinessProbe:
          httpGet:
            path: /readiness
            port: 9042
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "10Gi"
